// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seevhwbtwygjbhofhfjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlZXZod2J0d3lnamJob2ZoZmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjk5NDEsImV4cCI6MjA2NTg0NTk0MX0.uHEMm7LqSTWcBp_8xmGpUmOVjkGVOITJ1yYZdELNhi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);